my_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #Ruta de donde nos va a buscar las urls
    path("",include("productos.urlsProducts")),
    path("",include("carrito.urlsCarrito")),
    path("accounts/",include("accounts.urlsAccount")),
    path("admin/", admin.site.urls),
    #Comando especifico, para permitir las imagenes
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

productos/models.py
from django.db import models
from django.utils import timezone
#Modelo de la base de datos

class Producto(models.Model):
    name=models.CharField(max_length=50)
    price=models.DecimalField(decimal_places=2,max_digits=10)
    sku=models.CharField(max_length=10)
    category=models.CharField(max_length=20)
    #Referenciando Tablas
    brand=models.ForeignKey(
        "productos.Brand",
        on_delete=models.CASCADE,
        related_name="fk_brand"
    )
    #puede ser vacio y nulo, donde se va a guardar las imagenes
    image=models.ImageField(blank=True,null=True,upload_to="media/productos")
    discount=models.IntegerField(blank=True,null=True)
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)
    last_update=models.DateTimeField(blank=True,null=True)
    #como se mostrara el objeto, cuando lo mostremos
    def __str__(self) -> str:
        return f"{self.name}, marca=>{self.brand} , codigo=> {self.sku}"
    

class Brand(models.Model):
    name=models.CharField(max_length=30)
    description=models.TextField(null=True,blank=True)
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)
    last_update=models.DateTimeField(blank=True,null=True)
    logo=models.ImageField(blank=True,null=True,upload_to="media/productos")
    def __str__(self) -> str:
        return f"{self.name}"


class Comment(models.Model):
    #un producto puede tener muchos comentarios
    product=models.ForeignKey(
        #haciendo referencia al archivo y al nombre de la clase
        'productos.Producto',
        on_delete=models.CASCADE,
        related_name='fk_producto'
    )
    author=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    approved_comment=models.BooleanField(default=False)
    def approve(self):
        #Que lo ponga en true y lo guarde
        self.approved_comment=True
        self.save()
    def __str__(self) -> str:
        return self.text

templates/fecha.html
{%extends './base/root.html'%} 
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirmar compra</button>
</form>
        
{% endblock %}

templates/list_products.html
{%extends './base/root.html'%}
{% block content %}
        <div class="container">
            <div class="row">
                {%for product in products%}
                    <div class="col-3">
                        <div class="card">
                            <img src="{{product.image.url}}"
                                class="card-img-top float-start">
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <div class="price-container">
                                    <p class="card-title product-price">{{product.price}} USD</p>
                                </div>
                                <!--Forma de direccionar a otra url-->
                                <a class="btn btn-tomato" href={% url 'get_product' id=product.id %}>Leer más</a>
                            </div>
                        </div>
                        
                    </div>
                {%endfor%}
            </div>
        </div>
{%endblock%}

templates/show_product.html
{%extends './base/root.html'%} 
{% block content %}
    <div class="container">
        <div class="row product-detail-row mt-4 mb-5">
            <div class="col-5">
                <img src={{product.image.url}}
                     class="img-fluid"
                     height="">
            </div>
            <div class="col-7">
                <div class="jumbotron">
                    <h1 class="display-4"> {{ product.name }} </h1>
                    <div class="price-container">
                            <h5 class="card-title">
                                {{product.price}} USD
                            </h5>
                    </div>
                    <p>Incluye al animador</p>
                    <hr class="my-4">
                    <h3>
                      Animador: {{ product.brand.name }}
                    </h3>
                    <img src="{{ product.brand.logo.url }}"
                    class="img-fluid w-25"
                    alt="Logo de la marca">
                    <p>
                        {{ product.brand.description }}
                    </p>
                    <form action="{% url 'comprar' idProducto=product.id idBrand=product.brand.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-tomato">Comprar</a>
                    </form>
                </div>
            </div>
        </div>
        {% if perms.productos.add_comment %}
        <div class="row">
          <div class="col-5 comment-column">
            <form action="{% url 'new_comment' id=product.id %}" method="post" class="post-form">
              {% csrf_token %}
              <div class="input-group mb-4">
                {{ formCo.text }}
              </div>
              <button type="submit" class="save btn btn-dark">Enviar</button>
            </form>
          </div>
        </div>
        {%else%}
          <h1>INICIA SESION PARA COMENTAR</h1>
          <a  href="{%url 'login'%}" >Login</a> 
        {% endif%}
        <!--si tienes el permiso de ver los comentarios-->
        {% if perms.productos.view_comment %}
        <div class="col-7">
          <h2 class="comment-title text-left">Comentarios</h2>
          {% for comment in comments %}
            <div class="comment">
              <div class="date">{{ comment.created_date }}</div>
              <strong>{{ comment.author }}</strong>
              <p>{{ comment.text }}</p>
            </div>
          {% endfor %}
        </div>
        {%endif%}
        
{% endblock %}